version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
  worker:
    image: node
    volumes:
      - ./worker:/var/worker
    working_dir: /var/worker
    command: "npm run start"
